[project]
name = "AI-Algorithm-Mentor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai[tools]>=0.201.1",
    "python-dotenv>=1.0.0",
    "beautifulsoup4==4.12.3",
    "httpx==0.27.0",
    "pydantic==2.12.4",
]
