[project]
name = "AI-Algorithm-Mentor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai[tools]>=0.201.1",
    "python-dotenv>=1.0.0",
]
